### ISSUE TITLE
Autoship configuration??

### ISSUE THREAD

**Issue by puternutt** [GigaC/autoship#1]
I haven't seen any updates on this plugin since the last upload around Nov 2016, I grabbed the download of it and installed it into the latest WordPress with WooCommerce, but even though a tab shows up in the WooCommerce Settings, There is nothing there but a save changes button. 

What all does this or is this plugin supposed to do? Are you still actively working on the plugin and if you are can you update the github files?

**Comment by GigaC** [comment]
Sorry but the project is not finished, and I guess it won't be finished. And this is not a working version. @puternutt
